# Generated by Django 5.1.6 on 2025-02-20 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='access_code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='code_expiration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_researcher',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professional')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.researcher')),
            ],
        ),
        migrations.AddField(
            model_name='researcher',
            name='accessed_codes',
            field=models.ManyToManyField(through='users.ResearcherAccess', to='users.professional'),
        ),
    ]
