# Generated by Django 5.1.6 on 2025-02-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_professional_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='current_projects',
            field=models.TextField(blank=True, help_text='Projets de recherche en cours', null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='publications',
            field=models.TextField(blank=True, help_text='Liste des publications', null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='research_domain',
            field=models.CharField(blank=True, help_text='Domaine de recherche principal', max_length=100, null=True),
        ),
    ]
