# Generated by Django 5.1.6 on 2025-02-23 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_researcher_current_projects_researcher_publications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='users.professional')),
            ],
        ),
    ]
