# Generated by Django 5.1.6 on 2025-02-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='access_code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='license_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
