# Generated by Django 5.1.6 on 2025-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_researcheraccess_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcheraccess',
            name='temporary_field',
            field=models.BooleanField(default=False),
        ),
    ]
