# Generated by Django 5.1.6 on 2025-02-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_researcheraccess_temporary_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcheraccess',
            name='temporary_field',
        ),
    ]
